version: "3.8"

services:
  pizzaapp:
    image: erhnaks/pizzaapp:latest
    environment:
      DATABASE_URI: ${MY_DATABASE}
      KEY: ${MY_SECRET_KEY}
    ports:
    - target: 5000
      published: 5000
      protocol: tcp

  mysql_container:
    image: mysql:5.7
    ports:
    - target: 3306
      published: 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
    - type: volume
      source: pizza
      target: /var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: nginx/nginx.conf
      target: /etc/nginx/nginx.conf

volumes:
  pizza: