version: "3.8"
services:
  backend:
    deploy:
      replicas: 3
    build: ./
    image: ${DOCKER_HUB_CREDS_USR}/pizza-app:latest
    container_name: pizza-app
    environment:
      DATABASE_URI:
      CREATE_SCHEMA:
    ports:
    - target: 5000
      published: 5000




# version: "3.8"

# services:
#   pizzaapp:
#     image: pizza_pizza:latest
#     ports:
#     - target: 5000
#       published: 5000
#       protocol: tcp

#   mysql_container:
#     image: mysql:5.7
#     ports:
#     - target: 3306
#       published: 3306
#     environment:
#       MYSQL_ROOT_PASSWORD: pizza123
#       MYSQL_DATABASE: chefdb
#     volumes:
#     - type: volume
#       source: pizza
#       target: /var/lib/mysql

#   nginx:
#     image: nginx:latest
#     ports:
#     - target: 80
#       published: 80
#       protocol: tcp
#     volumes:
#     - type: bind
#       source: nginx/nginx.conf
#       target: /etc/nginx/nginx.conf

# volumes:
#   pizza: